#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

wclean libso phaseSystems
wclean libso interfacialModels
wclean libso interfacialCompositionModels
wclean libso multiphaseCompressibleMomentumTransportModels
wclean libso multiphaseThermophysicalTransportModels
jouleHeatingMultiphaseEulerFoam/Allwclean
wclean libso functionObjects

#------------------------------------------------------------------------------
